name: Run Tests on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run Tests
        run: pytest service 

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth

      - name: Run Snyk tests
        run: snyk test 

      - name: Build Docker Image
        run: docker build -t sample-backend:latest .
        working-directory: ${{ github.workspace }}/Graticule_assignment

      - name: Run Snyk Docker Scan
        run: snyk container sample-backend:latest
