name: Run Python tests and perform Snyk scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: pip install -e '.[dev]'

      - name: Run Tests
        run: pytest service

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install and Run Snyk Scan
        run: |
          snyk test
          SNYK_EXIT_CODE=$?
          if [ $SNYK_EXIT_CODE -eq 1 ]; then
            echo "Snyk vulnerabilities found, but workflow will continue."
            exit 0
          fi
        continue-on-error: true

      - name: Build Docker Image
        run: docker build -t sample-backend:latest .
        working-directory: ${{ github.workspace }}

      - name: Run Snyk Docker Scan
        run: snyk container sample-backend:latest

      - name: Monitor Snyk Results
        run: DEBUG=*snyk* snyk monitor --all-projects