name: Run Tests on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run Tests
        run: pytest service 
